#!/usr/bin/env python3
"""Medium daily hot topics scraper."""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import feedparser
from bs4 import BeautifulSoup
from rich.console import Console
from rich.table import Table
from rich import box

TOPICS = {
    "AI": "https://medium.com/feed/tag/artificial-intelligence",
    "LLM": "https://medium.com/feed/tag/llm",
    "Claude": "https://medium.com/feed/tag/claude-ai",
    "ChatGPT": "https://medium.com/feed/tag/chatgpt",
    "Gemini": "https://medium.com/feed/tag/google-gemini",
    "Architecture": "https://medium.com/feed/tag/software-architecture",
    "Crypto": "https://medium.com/feed/tag/cryptocurrency",
    "BTC": "https://medium.com/feed/tag/bitcoin",
}

TOP_N = 3
OUTPUT_DIR = Path(__file__).parent / "output"
README_PATH = Path(__file__).parent / "README.md"
console = Console()


def strip_html(html: str) -> str:
    if not html:
        return ""
    soup = BeautifulSoup(html, "html.parser")
    text = soup.get_text(separator=" ").strip()
    # Collapse whitespace
    return " ".join(text.split())


def parse_date(entry) -> datetime:
    """Parse published date from feed entry, return UTC datetime."""
    for attr in ("published_parsed", "updated_parsed"):
        t = getattr(entry, attr, None)
        if t:
            try:
                return datetime(*t[:6], tzinfo=timezone.utc)
            except Exception:
                pass
    return datetime(1970, 1, 1, tzinfo=timezone.utc)


def fetch_topic(topic: str, url: str) -> list[dict]:
    console.print(f"  Fetching [cyan]{topic}[/cyan] ...", end=" ")
    try:
        feed = feedparser.parse(url)
        entries = feed.entries
        console.print(f"[green]{len(entries)} entries[/green]")
    except Exception as e:
        console.print(f"[red]ERROR: {e}[/red]")
        return []

    articles = []
    for entry in entries:
        summary_raw = getattr(entry, "summary", "") or ""
        summary = strip_html(summary_raw)
        # Trim to 300 chars
        if len(summary) > 300:
            summary = summary[:297] + "..."

        pub_dt = parse_date(entry)
        articles.append({
            "topic": topic,
            "title": entry.get("title", "").strip(),
            "url": entry.get("link", "").strip(),
            "summary": summary,
            "published": pub_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "_pub_dt": pub_dt,
        })

    # Sort descending by date, keep top N
    articles.sort(key=lambda a: a["_pub_dt"], reverse=True)
    return articles[:TOP_N]


def build_readme(articles_by_topic: dict[str, list[dict]], today: str) -> str:
    lines = [
        "# Medium Daily Digest",
        "",
        "Auto-updated daily snapshot of hot articles from Medium across key topics.",
        "",
        "**Topics:** " + ", ".join(TOPICS.keys()),
        "",
        f"## Latest digest: {today}",
        "",
    ]

    for topic, articles in articles_by_topic.items():
        lines.append(f"### {topic}")
        lines.append("")
        lines.append("| Title | Summary | Published |")
        lines.append("|-------|---------|-----------|")
        for a in articles:
            title_link = f"[{a['title']}]({a['url']})"
            summary_snippet = a["summary"][:120].replace("|", "\\|") + ("..." if len(a["summary"]) > 120 else "")
            lines.append(f"| {title_link} | {summary_snippet} | {a['published'][:10]} |")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by scraper.py on {today}*")
    lines.append("")
    return "\n".join(lines)


def git_commit_push(today: str):
    json_file = f"output/{today}.json"
    try:
        result = subprocess.run(
            ["git", "add", json_file, "README.md"],
            cwd=Path(__file__).parent,
            capture_output=True, text=True
        )
        if result.returncode != 0:
            console.print(f"[yellow]git add warning:[/yellow] {result.stderr.strip()}")

        result = subprocess.run(
            ["git", "commit", "-m", f"Daily digest {today}"],
            cwd=Path(__file__).parent,
            capture_output=True, text=True
        )
        if result.returncode != 0:
            console.print(f"[yellow]git commit warning:[/yellow] {result.stderr.strip()}")
            return

        console.print(f"[green]Committed:[/green] Daily digest {today}")

        result = subprocess.run(
            ["git", "push", "origin", "main"],
            cwd=Path(__file__).parent,
            capture_output=True, text=True
        )
        if result.returncode != 0:
            console.print(f"[yellow]git push warning:[/yellow] {result.stderr.strip()}")
        else:
            console.print("[green]Pushed to origin/main[/green]")
    except FileNotFoundError:
        console.print("[yellow]git not found — skipping commit/push[/yellow]")


def print_table(articles_by_topic: dict[str, list[dict]]):
    table = Table(
        title="Medium Daily Hot Topics",
        box=box.ROUNDED,
        show_lines=True,
        expand=True,
    )
    table.add_column("Topic", style="cyan bold", no_wrap=True, width=12)
    table.add_column("Title", style="white", min_width=30)
    table.add_column("Summary", style="dim", min_width=40)
    table.add_column("Published", style="green", no_wrap=True, width=12)
    table.add_column("URL", style="blue", no_wrap=False, min_width=20)

    for topic, articles in articles_by_topic.items():
        for i, a in enumerate(articles):
            table.add_row(
                topic if i == 0 else "",
                a["title"][:80],
                a["summary"][:120] + ("..." if len(a["summary"]) > 120 else ""),
                a["published"][:10],
                a["url"],
            )

    console.print(table)


def main():
    today = datetime.now().strftime("%Y-%m-%d")
    OUTPUT_DIR.mkdir(exist_ok=True)
    output_file = OUTPUT_DIR / f"{today}.json"

    console.rule(f"[bold cyan]Medium Scraper — {today}[/bold cyan]")

    all_articles: list[dict] = []
    seen_urls: set[str] = set()
    articles_by_topic: dict[str, list[dict]] = {}

    for topic, url in TOPICS.items():
        articles = fetch_topic(topic, url)
        deduped = []
        for a in articles:
            if a["url"] not in seen_urls:
                seen_urls.add(a["url"])
                deduped.append(a)
        articles_by_topic[topic] = deduped
        all_articles.extend(deduped)

    # Strip internal _pub_dt before saving
    save_data = [{k: v for k, v in a.items() if k != "_pub_dt"} for a in all_articles]

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(save_data, f, indent=2, ensure_ascii=False)
    console.print(f"\n[bold green]Saved {len(save_data)} articles to {output_file}[/bold green]")

    # Update README
    readme_content = build_readme(articles_by_topic, today)
    README_PATH.write_text(readme_content, encoding="utf-8")
    console.print(f"[bold green]Updated {README_PATH}[/bold green]")

    # Terminal table
    console.print()
    print_table(articles_by_topic)

    # Git commit + push
    console.print()
    git_commit_push(today)


if __name__ == "__main__":
    main()
